### ISSUE TITLE
Error when run example/reference

### ISSUE THREAD

**Issue by gaocegege** [gaocegege/Processing.R#106]
org.renjin.eval.EvalException: Cannot match arguments (double) to any JVM method overload:
	public void processing.core.PApplet.ellipseMode(int)
	at org.renjin.invoke.reflection.FunctionBinding.invoke(FunctionBinding.java:179)
	at org.renjin.invoke.reflection.FunctionBinding.evaluateArgsAndInvoke(FunctionBinding.java:158)
	at org.renjin.invoke.reflection.MethodFunction.apply(MethodFunction.java:58)
	at org.renjin.eval.Context.evaluateCall(Context.java:368)
	at org.renjin.eval.Context.evaluate(Context.java:256)
	at org.renjin.eval.Context.evaluateExpressionVector(Context.java:351)
	at org.renjin.eval.Context.evaluate(Context.java:254)
	at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:168)
	at org.renjin.script.RenjinScriptEngine.eval(RenjinScriptEngine.java:127)
	at rprocessing.RLangPApplet.setup(Unknown Source)
	at processing.core.PApplet.handleDraw(PApplet.java:2414)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1547)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)

**Comment by gaocegege** [comment]
Close via #104
