### ISSUE TITLE
size fails in setup

### ISSUE THREAD

**Issue by gaocegege** [gaocegege/Processing.R#39]
```R
setup <- function()
{
    processing$size(200,200)
}
```

```
org.renjin.eval.EvalException: size() cannot be used here, see https://processing.org/reference/size_.html
	at org.renjin.eval.Context.evaluateCall(Context.java:307)
	at org.renjin.eval.Context.evaluate(Context.java:218)
	at org.renjin.primitives.special.BeginFunction.apply(BeginFunction.java:46)
	at org.renjin.eval.Context.evaluateCall(Context.java:298)
	at org.renjin.eval.Context.evaluate(Context.java:218)
	at org.renjin.eval.Context.evaluate(Context.java:165)
	at org.renjin.sexp.Closure.doApply(Closure.java:107)
	at rprocessing.RLangPApplet.setup(RLangPApplet.java:158)
	at processing.core.PApplet.handleDraw(PApplet.java:2395)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1540)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)
Caused by: java.lang.IllegalStateException: size() cannot be used here, see https://processing.org/reference/size_.html
	at processing.core.PApplet.insideSettings(PApplet.java:938)
	at processing.core.PApplet.size(PApplet.java:1981)
	at rprocessing.applet.BuiltinApplet.size(BuiltinApplet.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.renjin.invoke.reflection.FunctionBinding$Overload.invoke(FunctionBinding.java:90)
	at org.renjin.invoke.reflection.FunctionBinding.invoke(FunctionBinding.java:149)
	at org.renjin.invoke.reflection.FunctionBinding.evaluateArgsAndInvoke(FunctionBinding.java:131)
	at org.renjin.invoke.reflection.MethodFunction.apply(MethodFunction.java:41)
	at org.renjin.eval.Context.evaluateCall(Context.java:298)
	... 10 more
```

**Comment by jeremydouglass** [comment]
This *might* be related to the preprocessor.

I could be wrong, but it is possible that ~Processing 3.0+ uses the preprocessor to move size() from setup() into settings(). The mechanism may be slightly different then the simplified way it is explained in the public reference:

-  https://processing.org/reference/settings_.html
-  https://processing.org/reference/setup_.html
-  https://processing.org/reference/size_.html

**Comment by gaocegege** [comment]
I have implemented a simple pre-processor [here](https://github.com/gaocegege/Processing.R/blob/8d02cde1ffcdcd7c2099f9ea7361c050d58571af/src/rprocessing/RLangPApplet.java#L80)

I am not sure if it works in this situation. I will have a look soon.

**Comment by jeremydouglass** [comment]
Possibly related example of the Java preprocessor:

https://github.com/processing/processing/issues/5065#issuecomment-301937452

**Comment by gaocegege** [comment]
Related with #51 or #9

**Comment by gaocegege** [comment]
dup with #51
